export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";

export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS";
export const CREATE_CASE = "CREATE_CASE";
export const EDIT_CASE_SUCCESS = "EDIT_CASE_SUCCESS";
export const DELETE_CASE_SUCCESS = "DELETE_CASE_SUCCESS";
export const GET_ONE_CASE_SUCCESS = "GET_ONE_CASE";

export const FETCH_OFFICERS_SUCCESS = "FETCH_OFFICERS_SUCCESS";
export const DELETE_OFFICER_SUCCESS = "DELETE_CASE_SUCCESS";
export const EDIT_OFFICER_SUCCESS = "EDIT_OFFICER_SUCCESS";
